### ISSUE TITLE
Error while updating channels

### ISSUE THREAD

**Issue by ovargasp** [cabernetwork/provider_video_daddylive#56]
I'm using the docker version, and I just noticed that the plugin is giving an error while finishing the update process, I restarted cabernet 3 times to make sure it wasn't due any other problem, it seems it goes all the way processing the channels, says how many it found and the presents this error:

2025-03-05 02:26:04,259-INFO:channels DaddyLive:default 2 Updating Channel 360:5 USA
2025-03-05 02:26:05,140-INFO:channels DaddyLive:default 2 Updating Channel 726:3sat DE
2025-03-05 02:26:05,141-INFO:channels DaddyLive: Found 752 stations on instance default
2025-03-05 02:26:05,143-ERROR:scheduler UNEXPECTED EXCEPTION on GET=Error binding parameter 7 - probably unsupported type.
Traceback (most recent call last):
  File "/app/lib/schedule/scheduler.py", line 157, in call_trigger
    results = call_f()
  File "/app/lib/plugins/plugin_obj.py", line 225, in refresh_channels
    return self.refresh_it('Channels', _instance)
  File "/app/lib/plugins/plugin_obj.py", line 248, in refresh_it
    instance.refresh_channels()
  File "/app/lib/plugins/plugin_instance_obj.py", line 152, in refresh_channels
    return self.channels.refresh_channels()
  File "/app/lib/plugins/plugin_channels.py", line 145, in refresh_channels
    self.db.save_channel_list(
  File "/app/lib/db/db_channels.py", line 221, in save_channel_list
    self.add(DB_CHANNELS_TABLE, (
  File "/app/lib/db/db.py", line 94, in add
    self.sql_exec(sqlcmd, _values, cur)
  File "/app/lib/db/db.py", line 66, in sql_exec
    return _cursor.execute(_sqlcmd, _bindings)
sqlite3.InterfaceError: Error binding parameter 7 - probably unsupported type.

in the UI it then says it didn't run:

![Image](https://github.com/user-attachments/assets/ce684a9d-9df9-4d8c-aaca-7a2318dc1fd8)

It used to run fine about a week ago. Any Ideas???

**Comment by macman2034** [comment]
I havnt watched any of the daddylive channels for about a week and just tried firing a few of them up and none of them are working tonight, everything's fine from the xumo and pluto ones however. And through the daddy live site it works, but I think their domain has changed since I last visited their site about a month ago when a similar issue happened.

**Comment by rocky4546** [comment]
All works fine here.

**Comment by ovargasp** [comment]
Thanks Rocky4546, I did a little digging and what I think I found is that I enabled the  "Import Channel Groups" in the daddylife instance (I don't know exactly when or why) but by doing that the value of the group is not a string but an array, and that seems to cause the binding parameter 7 issue. I disabled it and  now it is working, I don't know if is just me, or is what happens if you do that. 

here are some examples:

2025-03-05 22:03:36,123-INFO:db SQL Command: 
        INSERT INTO channels (
            namespace, instance, enabled, uid, number, display_number, display_name,
            group_tag, thumbnail, thumbnail_size, updated, json
            ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
        , Values: ('DaddyLive', 'default', True, '148', 588, 588, 'Sport 5 Gold Israel', **['P1P2']**, None, 'None', True, '{"id": "148", "enabled": 1, "callsign": "148", "number": 588, "name": "Sport 5 Gold Israel", "display_name": "Sport 5 Gold Israel", "HD": 0, "group_hdtv": null, "group_sdtv": null, "groups_other": ["P1P2"], "thumbnail": null, "thumbnail_size": null, "VOD": false, "Header": {"User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36", "Referer": "https://pkpakiplay.xyz/", "Origin": "https://pkpakiplay.xyz"}, "ref_url": "https://pkpakiplay.xyz/", "use_date_on_m3u8_key": false}')
2025-03-05 22:03:36,274-INFO:db UNEXPECTED EXCEPTION on GET=Error binding parameter 7 - probably unsupported type.

2025-03-05 22:03:36,123-INFO:db SQL Command: 
        INSERT INTO channels (
            namespace, instance, enabled, uid, number, display_number, display_name,
            group_tag, thumbnail, thumbnail_size, updated, json
            ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
        , Values: ('DaddyLive', 'default', True, '881', 580, 580, 'Sky UNO Italy', **['P1P2P3P4']**, None, 'None', True, '{"id": "881", "enabled": 1, "callsign": "881", "number": 580, "name": "Sky UNO Italy", "display_name": "Sky UNO Italy", "HD": 0, "group_hdtv": null, "group_sdtv": null, "groups_other": ["P1P2P3P4"], "thumbnail": null, "thumbnail_size": null, "VOD": false, "Header": {"User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36", "Referer": "https://pkpakiplay.xyz/", "Origin": "https://pkpakiplay.xyz"}, "ref_url": "https://pkpakiplay.xyz/", "use_date_on_m3u8_key": false}')
2025-03-05 22:03:36,124-INFO:db UNEXPECTED EXCEPTION on GET=Error binding parameter 7 - probably unsupported type.

**Comment by rocky4546** [comment]
Thanks, This is a great help.  I will take a look at that.

**Comment by GiviMAD** [comment]
Hello,

I also facing a similar issue, I think is caused by the official docker image using python:3.8-alpine while the code in the plugin has been updated to work with a newer python version.

I see these on the log:
```
...
  File "/app/plugins_ext/provider_video_daddylive/lib/channels.py", line 333, in get_tvg_reference

    importlib.resources.files(resources).joinpath('channel_list.json').read_text())

AttributeError: module 'importlib.resources' has no attribute 'files'
```

**Comment by ovargasp** [comment]
I can't reproduce the error... I have plugin version 0.1.46 (latest), I just ran it and it worked as expected.

Are you running the docker image???

**Comment by GiviMAD** [comment]
Yes I'm using the docker image ghcr.io/cabernetwork/cabernet:latest.
I downgraded to plugin version 0.1.45 and the task succeeded.

**Comment by rocky4546** [comment]
Hi all, the latest version has changes to support python 3.13.  It also is working on my Ubuntu python, version 3.10.  If someone would like to create and test a PR with python version 3.10 and see if it will work with the latest version, that would be awesome.  Thanks.

**Comment by trzachan** [comment]
i made a test: i added python 3.12 upgrade command into dockerfile and rebuilt the container

then i "bash-ed" to alpine linux 

anyway, cabernet uses his own /usr/local/bin/python 3.8  instead of /usr/bin/python (now 3.12 ver)
i attempted to symlink /usr/local/bin/python pointing out to /usr/bin, restarted the container...but it no more runs (errors)
so i reverted back to original situation

**Comment by mfirewire** [comment]
I got the same error on updating. The encoding is UTF-8 like that
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

And the first run of the plug-in is OK. The error occurs in updating. The detailed log is as follows: 

2025-04-23 09:33:28,507-INFO:channels DaddyLive:default 2 New Channel Added 520:18+ (Player-20)
2025-04-23 09:33:29,360-INFO:channels DaddyLive: Found 753 stations on instance default
2025-04-23 09:33:29,363-ERROR:scheduler UNEXPECTED EXCEPTION on GET=Error binding parameter 7 - probably unsupported type.
Traceback (most recent call last):
  File "/app/lib/schedule/scheduler.py", line 157, in call_trigger
    results = call_f()
  File "/app/lib/plugins/plugin_obj.py", line 225, in refresh_channels
    return self.refresh_it('Channels', _instance)
  File "/app/lib/plugins/plugin_obj.py", line 248, in refresh_it
    instance.refresh_channels()
  File "/app/lib/plugins/plugin_instance_obj.py", line 152, in refresh_channels
    return self.channels.refresh_channels()
  File "/app/lib/plugins/plugin_channels.py", line 145, in refresh_channels
    self.db.save_channel_list(
  File "/app/lib/db/db_channels.py", line 221, in save_channel_list
    self.add(DB_CHANNELS_TABLE, (
  File "/app/lib/db/db.py", line 94, in add
    self.sql_exec(sqlcmd, _values, cur)
  File "/app/lib/db/db.py", line 66, in sql_exec
    return _cursor.execute(_sqlcmd, _bindings)
sqlite3.InterfaceError: Error binding parameter 7 - probably unsupported type.

Pls help to find a solution.

**Comment by ovargasp** [comment]
in the plugin unselect/uncheck the import channel  groups and try again

![Image](https://github.com/user-attachments/assets/10cfaf02-68e9-4016-894d-1798730da3a6)

**Comment by mfirewire** [comment]
> in the plugin instance unselect/uncheck the import channel groups and try again
> 
> ![Image](https://github.com/user-attachments/assets/10cfaf02-68e9-4016-894d-1798730da3a6)

Great! It works!
Thank you so much!

**Comment by ovargasp** [comment]
@trzachan do you mind sharing your docker compose file?? I still can't reproduce the error, and everything works fine on my docker instance; importlib.resources.files was indeed removed in python 3.11 but it should work because latest cabernet docker still uses version 3.8 so it seems somehow your docker version has a newer version of python...

**Comment by trzachan** [comment]
sure, ovar,

i got this compose file

```
# Things to review/change:
#    PUID/PGID change to the user running Cabernet
#    Volumes: All volume paths are to be updated.  The secrets folder
#    contains the private key for encryption and should be protected.
#    example volumes:
#          - ../docker/cabernet/data:/app/data                # App data (Optional)
#          - ../docker/cabernet/plugins_ext:/app/plugins_ext  # Plugins Data (Optional)
#          - ../docker/cabernet/secrets:/app/.cabernet        # Ecryption key data (Optional)
#    This will add a docker folder at the same level as the cabernet source
#    with the external folders for docker

#version: '2.4'
services:
  cabernet:
    container_name: cabernet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ="Etc/UTC"
      - PUID=1000
      - PGID=1000
    ports:
      - "6077:6077"
      - "5004:5004"
    restart: unless-stopped
    volumes:
      - /home/jib/cfg/cabernet/data:/app/data
      - /home/jib/cfg/cabernet/plugins_ext:/app/plugins_ext
      - /home/jib/cfg/cabernet/secrets:/app/.cabernet
```

and my dockerfile (built from scratch to upgrad python3)

```
ROM ghcr.io/cabernetwork/cabernet:latest

# Rimuovi la vecchia versione di Python e installa quella nuova
RUN apk update && \
    apk del python3 && \
    apk add --no-cache python3=3.12.10-r0 py3-pip

# Crea i symlink per python3 e pip3
#RUN ln -sf /usr/bin/python3 /usr/local/bin/python3 && \
#    ln -sf /usr/bin/pip3 /usr/local/bin/pip3

# Verifica la versione
RUN python3 --version

```


but bear in mind that once rebuilt imag, i got python3.12 in /usr/bin for alpine linux subsystem
but i found that cabernet once started again, performs a pip installation of python 3.8 in /usr/local/bin...and that's the interpreter it uses for executing its own .py files...(such as task scheduling, etc)

i also tried to "cheat" cabernet symlinking /usr/local/bin/python3 to /usr/bin/python3 (the new ver) ..in order to make scheduler.py from daddy_live_plugin (new ver) work back again but...after this mod, cabernet didn't work at all once restarted :-( so i had to roll back to original situation...but still with latest channel refresh issue

**Comment by ovargasp** [comment]
OK, but it seems it actually uses the new version of python... the 3.12.10 you're installing (there is a documented change in version 3.12 importlib.resources.files and that can be the issue). Did you tried: docker exec -it <cabernet-docker name> python --version to check what python version is being used?? or maybe start with version 3.10 or 3.11 instead of going directly to 3.12

**Comment by trzachan** [comment]
well look slike it's still using the old python version, even though i installed python 3.12, cos /usr/local/bin/python has precedence on /usr/bin (it'd look like!)
```
[jib@Pipon ~]$  docker exec -it cabernet /bin/bash
70d52b3d1813:/app# python
python            python-config     python3           python3-config    python3.12        python3.8         python3.8-config  
70d52b3d1813:/app# python3 --version
Python 3.8.20
70d52b3d1813:/app# which python
/usr/local/bin/python
70d52b3d1813:/app# /usr/bin/python3 --version
Python 3.12.10
70d52b3d1813:/usr/local/bin# ls -al python*
lrwxrwxrwx    1 root     root             7 Sep 12  2024 python -> python3
lrwxrwxrwx    1 root     root            14 Sep 12  2024 python-config -> python3-config
lrwxrwxrwx    1 root     root             9 Sep 12  2024 python3 -> python3.8
lrwxrwxrwx    1 root     root            16 Sep 12  2024 python3-config -> python3.8-config
-rwxr-xr-x    1 root     root         14024 Sep 12  2024 python3.8
-rwxr-xr-x    1 root     root          3029 Sep 12  2024 python3.8-config
70d52b3d1813:/usr/local/bin# cd /usr/bin
70d52b3d1813:/usr/bin# ls -al pyth*
lrwxrwxrwx    1 root     root             7 Apr 22 16:07 python -> python3
lrwxrwxrwx    1 root     root            10 Apr 22 16:07 python3 -> python3.12
-rwxr-xr-x    1 root     root         14080 Apr  9 07:23 python3.12

```

**Comment by trzachan** [comment]
anyway in alpine linux subsystem i didn't find python3 vers prior to 3.12 to install, unfortunately

 '''
70d52b3d1813:/usr/bin# apk search python
..etc..
python3-3.12.10-r0
python3-dbg-3.12.10-r0
python3-dev-3.12.10-r0
python3-doc-3.12.10-r0
python3-gdbm-3.12.10-r0
python3-idle-3.12.3-r0
python3-pyc-3.12.10-r0
python3-pycache-pyc0-3.12.10-r0
python3-pycache-pyc1-3.12.10-r0
python3-pycache-pyc2-3.12.10-r0
python3-tests-3.12.10-r0
python3-tkinter-3.12.3-r0
python3-tkinter-pyc-3.12.3-r0
python3-tkinter-tests-3.12.3-r0
..etc..
```

**Comment by ovargasp** [comment]
I see... What I would do instead in that case is clone the whole repository and use the original docker file changing the python-alpine image, first to 3.10, that I've used for other projects, and then 3.12 to see if that way works, I can try that later when I get back home and let you know the results, but in the meantime if you want it running, just pull the image directly, no modifications, that should get things working again.

**Comment by ovargasp** [comment]
so @trzachan I did tried an alpine image with python 3.12 and it works with the daddylive pluggin version 1.1.46 and m3u pluggin 0.1.17. just 2 warnings on regex but that didn't affected functionality. Tests were using IPTV players both for android and linux. No tvheadend because I don't have nor use one.

this is the Dockerfile that I used to compile:

FROM python:3.12-alpine
WORKDIR /app
COPY . .
RUN apk add --no-cache --update bash tzdata ffmpeg curl su-exec && \
    apk add --no-cache --virtual builddeps gcc musl-dev python3-dev libffi-dev openssl-dev cargo && \
    pip3 install -r requirements.txt --no-cache-dir && \
    apk del builddeps && \
    touch /app/is_container && \
    mv Docker_entrypoint.sh /usr/local/bin && \
    rm -rf /tmp/* $HOME/.cache $HOME/.cargo

VOLUME /app/data /app/plugins_ext /app/.cabernet
EXPOSE 6077 5004
ENTRYPOINT ["Docker_entrypoint.sh"]

I checked python version of the docker
docker exec -it cabernet python --version
Python 3.12.10

so its safe to go to python 3.12. I'm going the tests in a VM and it takes a while for it to compile so you can do the same with alpine image 3.13 and see how it works...

**Comment by trzachan** [comment]
bingo! @ovargasp , i rebased cabernet container with latest alpine image and now all is working smoothly...i didn't have to recompile anything in this way

i did this way, roughly

my Dockerfile
----
```
FROM alpine:latest
RUN apk update && \
    apk del python3 && \
    apk add --no-cache python3=3.12.10-r0 py3-pip bash && \
    apk add py3-cryptography && \
    apk add streamlink && \
    apk add ffmpeg && \
    apk add py3-pip && \
    apk add su-exec && \
    cd /opt && \
    wget "https://github.com/cabernetwork/cabernet/archive/refs/tags/0.9.15.00-RC04.tar.gz" && \
    tar xvf 0.9.15.00-RC04.tar.gz && \
    cd cabernet-0.9.15.00-RC04 && \
    ln -s /opt/cabernet-0.9.15.00-RC04 /app
ENTRYPOINT ["/bin/sh", "/app/Docker_entrypoint.sh"]
```
---

my docker-compose.yml - in order to old cabernet data and cfg
---
```
# Things to review/change:
#    PUID/PGID change to the user running Cabernet
#    Volumes: All volume paths are to be updated.  The secrets folder
#    contains the private key for encryption and should be protected.
#    example volumes:
#          - ../docker/cabernet/data:/app/data                # App data (Optional)
#          - ../docker/cabernet/plugins_ext:/app/plugins_ext  # Plugins Data (Optional)
#          - ../docker/cabernet/secrets:/app/.cabernet        # Ecryption key data (Optional)
#    This will add a docker folder at the same level as the cabernet source
#    with the external folders for docker

#version: '2.4'
services:
  jib-cabernet:
    container_name: jib-cabernet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ="Europe/Rome"
      - PUID=1000
      - PGID=1000
    ports:
      - "6077:6077"
      - "5004:5004"
    restart: unless-stopped
    volumes:
      - /home/jib/cfg/cabernet/data:/app/data
      - /home/jib/cfg/cabernet/plugins_ext:/app/plugins_ext
      - /home/jib/cfg/cabernet/secrets:/app/.cabernet
```
---

hope can be helpful also for others needing to fix python3 problems during DL channels refresh

**Comment by jnoy** [comment]
Hi I just realized I had this issue as well. It appears I was able to fix the issue by rebuilding Cabernet, but all I had to do was in the dockerfile change from python 3.10 to 3.12
`FROM python:3.10.12-alpine` to `FROM python:3.12.10-alpine`
I am currently refreshing the channels after doing this.

**Comment by rocky4546** [comment]
Bug has been resolved as part of DL version 48.
